export enum OrderReasonCode {
  CUSTOMER_CHANGED_MIND = 'CUSTOMER_CHANGED_MIND',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  DUPLICATE_ORDER = 'DUPLICATE_ORDER',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REFUSED_ON_DELIVERY = 'REFUSED_ON_DELIVERY',
  DEFECTIVE = 'DEFECTIVE',
  WRONG_ITEM = 'WRONG_ITEM',
  BETTER_PRICE_FOUND = 'BETTER_PRICE_FOUND',
  OTHER = 'OTHER',
}
