export const ROUTES = {
    ATTRIBUTE: '/attribute',
    ATTRIBUTE_VALUE: '/attribute-value',
    CATEGORY: '/category',
    DASHBOARD: '/dashboard',
    INVENTORY: '/inventory',
    INVENTORY_LIST: '/inventory/list',
    INVENTORY_IMPORT: '/inventory/import',
    INVENTORY_IMPORT_CREATE: '/inventory/import/create',
    INVENTORY_EXPORT: '/inventory/export',
    INVENTORY_EXPORT_CREATE: '/inventory/export/create',
    INVENTORY_ADJUSTMENT: '/inventory/adjustment',
    INVENTORY_ADJUSTMENT_CREATE: '/inventory/adjustment/create',
    LOGIN: '/login',
    ORDER: '/order',
    ORDER_LIST: '/order/list',
    ORDER_RETURN_REQUEST: '/order/return-request',
    ORDER_STATUS_HISTORY: '/order/status-history',
    PAYMENT: '/payment',
    PRODUCT: '/product',
    STATISTIC: '/statistic',
    STATISTIC_ORDER: '/statistic/order',
    STATISTIC_PRODUCT: '/statistic/product',
    STATISTIC_REVENUE_PROFIT: '/statistic/revenue-profit',
    STATISTIC_STOCK: '/statistic/stock',
    STATISTIC_USER: '/statistic/user',
    WAREHOUSE: '/warehouse',
  };